version: '3'
services:
  nsq-admin:
    image: nsqio/nsq
    command: /nsqadmin -lookupd-http-address nsqlookupd-1:4161 -lookupd-http-address nsqlookupd-2:4261
    ports:
    - "4171:4171"
  nsqd-1:
    image: nsqio/nsq
    hostname: 127.0.0.1
    command: /nsqd -tcp-address 0.0.0.0:4150 -data-path /usr/local/nsq/bin/data --http-address 0.0.0.0:4151 -lookupd-tcp-address nsqlookupd-1:4160 -lookupd-tcp-address nsqlookupd-2:4260 -broadcast-address 127.0.0.1
    volumes:
    - "./data1:/usr/local/nsq/bin/data"
    ports:
    - "4150:4150"
    - "4151:4151"
  nsqd-2:
    image: nsqio/nsq
    hostname: 127.0.0.1
    command: /nsqd -tcp-address 0.0.0.0:4250 -data-path /usr/local/nsq/bin/data -http-address 0.0.0.0:4251 -lookupd-tcp-address nsqlookupd-1:4160 -lookupd-tcp-address nsqlookupd-2:4260 -broadcast-address=127.0.0.1
    volumes:
    - "./data2:/usr/local/nsq/bin/data"
    ports:
    - "4250:4250"
    - "4251:4251"
  nsqd-3:
    image: nsqio/nsq
    hostname: 127.0.0.1
    command: /nsqd -tcp-address 0.0.0.0:4350 -data-path /usr/local/nsq/bin/data --http-address 0.0.0.0:4351 -lookupd-tcp-address nsqlookupd-1:4160 -lookupd-tcp-address nsqlookupd-2:4260 -broadcast-address=127.0.0.1
    volumes:
    - "./data3:/usr/local/nsq/bin/data"
    ports:
    - "4354:4350"
    - "4355:4351"
  nsqlookupd-1:
    image: nsqio/nsq
    command: /nsqlookupd -http-address 0.0.0.0:4161 -tcp-address 0.0.0.0:4160 -broadcast-address nsqlookupd-1
    ports:
    - "4160:4160"
    - "4161:4161"
  nsqlookupd-2:
    image: nsqio/nsq
    command: /nsqlookupd -http-address 0.0.0.0:4261 -tcp-address 0.0.0.0:4260 -broadcast-address nsqlookupd-2
    ports:
    - "4260:4260"
    - "4261:4261"